### ISSUE TITLE
Question: Monitor Mode for bcm4339

### ISSUE THREAD

**Issue by DanielAW** [tuter/monmob#4]
Hi,

I'm currently trying to enable the monitor mode on the bcm4339 chipset in the Nexus 5. This is part of my master thesis. It would be great if I could ask you some questions. 
Is there a mail address which I can use to contact you?

You can contact me via: dwegemer@seemoo.tu-darmstadt.de

Thanks in advance :-)

**Comment by 6e726d** [comment]
I close the issue as we are already communicating through email.
